vm_name: 'dev'
box_name: 'precise64'
box_url: 'http://files.vagrantup.com/precise64.box'
ip: '10.10.10.100'
hostname: 'local.dev'
forward_agent: true
forwards:
  http:
    from: 80
    to: 80
  nginx:
    from: 8080
    to: 8080
  api:
    from: 9090
    to: 9090
  mysql:
    from: 3306
    to: 3306
  xdebug:
    from: 9000
    to: 9000
  livereload:
    from: 35729
    to: 35729
  memcached:
    from: 11211
    to: 11211
share_folders:
  shared:
    host_path: 'shared/'
    guest_path: '/srv'
    create: true
    type: 'nfs'
use_hostupdater: false
hostupdater_aliases: 'www.local.dev,tools.local.dev,mysql.local.dev,phpmyadmin.local.dev'
hostupdater_remove_on_suspend: true
use_cashier: false
use_salt_provisioner: true
salt_verbose: true
salt_update: stable
timezone_default_settings: 'Asia/Seoul'
locales:
  us:
    locale: en_US.UTF-8
  gb:
    locale: en_GB.UTF-8
  ko:
    locale: ko_KR.UTF-8

# SETTINGS FOR SALT - DO NOT DELETE THIS LINE
phpmyadmin:
  server_name: 'phpmyadmin.local.dev'
  server_admin: 'admin@local.dev'
  allow_from: '10.10.10.0/24'
  logs_dir: '/srv/logs/apache2/phpmyadmin'

# tools_vhost:
#   server_name: 'tools.local.dev'
#   doc_root:  '/srv/tools.local.dev'
#   server_admin: 'admin@local.dev'
#   allow_override: 'All'
#   allow_from: 'all'
#   allow_status: 'granted'
#   logs_dir: '/srv/logs/apache2/tools.local.dev'

mysql_server:
  root_username: 'root'
  root_password: 'root'
  bind_address: '127.0.0.1'
  version: '5.5'

php:
  php_upload_max_filesize: '200M'

memcached:
  memory: 128
  host: '127.0.0.1'
  port: 11211

apc:
  memory: 64

#Timezone settings for Webgrind
timezone: 'Asia/Seoul'