vm_name: 'dev'
box_name: 'precise64'
box_url: 'http://files.vagrantup.com/precise64.box'
ip: '10.10.10.100'
forward_agent: true
forwards:
  http:
    from: 80
    to: 8080
  # If updating this, please also update the nginx port config in the salt_settings.yml
  nginx:
    from: 8181
    to: 8181
  jekyll:
    from: 4000
    to: 4000
  middleman:
    from: 4567
    to: 4567
  redmon:
    from: 4568
    to: 4568
  expressjs:
    from: 3000
    to: 3000
  api:
    from: 9090
    to: 9090
  mysql:
    from: 3306
    to: 3306
    postgresql:
    from: 5432
    to: 5432
  xdebug:
    from: 9000
    to: 9000
  livereload:
    from: 35729
    to: 35729
  memcached:
    from: 11211
    to: 11211
  redis:
    from: 6379
    to: 6379
  mongodb:
    from: 27017
    to: 27017
  mongodb_web_status:
    from: 28017
    to: 28017
share_folders:
  shared:
    host_path: 'shared/'
    guest_path: '/srv'
    create: true
    type: 'nfs'
use_cashier: false
use_salt_provisioner: true
salt_verbose: true
salt_update: stable
timezone_default_settings: 'Asia/Seoul'
locales:
  us:
    locale: en_US.UTF-8
  gb:
    locale: en_GB.UTF-8
  ko:
    locale: ko_KR.UTF-8