vm_name: 'dev'
box_name: 'precise64'
box_url: 'http://files.vagrantup.com/precise64.box'
ip: '10.10.10.100'
forward_agent: true
forwards:
  http:
    from: 80
    to: 80
  nginx:
    from: 8080
    to: 8080
  jekyll:
    from: 4000
    to: 4000
  middleman:
    from: 4567
    to: 4567
  redmon:
    from: 4568
    to: 4568
  expressjs:
    from: 3000
    to: 3000
  api:
    from: 9090
    to: 9090
  mysql:
    from: 3306
    to: 3306
    postgresql:
    from: 5432
    to: 5432
  xdebug:
    from: 9000
    to: 9000
  livereload:
    from: 35729
    to: 35729
  memcached:
    from: 11211
    to: 11211
  redis:
    from: 6379
    to: 6379
  mongodb:
    from: 27017
    to: 27017
  mongodb_web_status:
    from: 28017
    to: 28017
share_folders:
  shared:
    host_path: 'shared/'
    guest_path: '/srv'
    create: true
    type: 'nfs'
use_hostupdater: false
hostupdater_aliases: 'www.local.dev,tools.local.dev,mysql.local.dev,phpmyadmin.local.dev,phppgadmin.local.dev'
hostupdater_remove_on_suspend: true
use_cashier: false
use_salt_provisioner: true
salt_verbose: true
salt_update: stable
timezone_default_settings: 'Asia/Seoul'
locales:
  us:
    locale: en_US.UTF-8
  gb:
    locale: en_GB.UTF-8
  ko:
    locale: ko_KR.UTF-8

# SETTINGS FOR SALT - DO NOT DELETE THIS LINE
phpmyadmin:
  server_name: 'phpmyadmin.local.dev'
  server_admin: 'admin@local.dev'
  allow_from: '10.10.10.0/24'
  logs_dir: '/srv/logs/apache2'

phppgadmin:
  server_name: 'phppgadmin.local.dev'
  server_admin: 'admin@local.dev'
  allow_from: '10.10.10.0/24'
  logs_dir: '/srv/logs/apache2'

mysql_server:
  root_username: 'root'
  root_password: 'root'
  bind_address: '127.0.0.1'
  version: '5.5'

postgresql:
  root_username: 'root'
  root_password: 'root'
  test_db_name: 'test'
  bind_address: '10.10.10.0/24'

nginx:
  port: 8080

php:
  php_upload_max_filesize: '200M'

memcached:
  memory: 128
  host: '127.0.0.1'
  port: 11211
  logs_base_dir: '/srv/logs/memcached'

# Configuration for /etc/redis/redis.conf file
redis:
  bind: '127.0.0.1'
  port: 6379
  logs_base_dir: '/srv/logs/redis'

mongodb:
  bind_ip: '127.0.0.1'
  port: 27017
  logs_base_dir: '/srv/logs/mongodb'

apc:
  memory: 64

#Timezone settings for Webgrind
timezone: 'Asia/Seoul'